export const theme = {
    border: {
        buttonRadius: "4px",
        inputRadius: "4px",
        cardRadius: "8px",
    },
    colors: {
        primary: "#E43D3D",
        lightPrimary: "#FDEAE9",
        darkenPrimary: "#b11818",
        black: "#000000",
        blue: "#2F80ED",
        green: "#27AE60",
        lightBlue: "#E0ECFD",
        brown: "#BA461C",
        gray: "#71828A",
        darkGray: "#636363",
        lightBlack: "#4A4A4A",
        lightGray: "#FAFAFA",
        lightGray2: "#AEAEAE",
        navy: "#273E71",
        orange: "#F55D25",
        pink: "#FFF7E6",
        red: "#D0021B",
        white: "#FFFFFF",
        yellow: "#F2C94C",
        lightYellow: "#FFF9E2",
        lightRed: "#FCE6E6",
        lightGreen: "#DFF3E7",
    },
};
